openapi: 3.0.3
info:
  title: "Documentação do módulo '@project.artifactId@'"
  description: |
    "@project.description@"
  version: "@project.version@"
servers:
  - url: 'https://localhost:3000'
    description: "servidor de testes locais"
paths:
  "/":
    get:
      description: "batata"
      responses:
        200:
          description: "retorna a batata"
          content:
            "application/json":
              schema:
                properties:
                  batata:
                    type: string
                    description: "batata"
