openapi: 3.0.3
info:
  title: "Documentação do módulo 'Challange'"
  description: |
    "Banco Pan - Backend Challange using SWAPI"
  version: "0.0.1"
servers:
  - url: 'https://localhost:3000'
    description: "servidor de testes locais"
paths:
  "/":
    get:
      description: "batata"
      responses:
        200:
          description: "retorna a batata"
          content:
            "application/json":
              schema:
                properties:
                  batata:
                    type: string
                    description: "batata"
